Repository SOEN341-winter2019/Team-Project, pull requests merged in 2019-02, with the labels that each got.

#63 Incuded a Windows CMD command
  README_BACKEND.md
Labels: Documentation

#69 Communication with back-end
  src/signup.html
  src/static/js/server_responses.js
  src/static/js/signup.js
Labels: Priotity: HIGH

#111 Travis mehrdad
  .gitignore
  .travis.yml
  requirements.txt
  tweeter/test_travisCI.py
Labels: Priotity: HIGH, Task
